// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzkNiNCdtycnM951MwaBih8Q3SKZKET5o',
    appId: '1:656885086584:web:fb1f65372248ee065cf08d',
    messagingSenderId: '656885086584',
    projectId: 'al-hashmi-market-z',
    authDomain: 'al-hashmi-market-z.firebaseapp.com',
    storageBucket: 'al-hashmi-market-z.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8vxp2QydXusgpzncjMAHcHxuKJsHEZhw',
    appId: '1:656885086584:android:8dd8701280a74fda5cf08d',
    messagingSenderId: '656885086584',
    projectId: 'al-hashmi-market-z',
    storageBucket: 'al-hashmi-market-z.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxEbm56znPalE-dbgUV9YQcmCdxZRetQ8',
    appId: '1:656885086584:ios:0aace132cfb99b075cf08d',
    messagingSenderId: '656885086584',
    projectId: 'al-hashmi-market-z',
    storageBucket: 'al-hashmi-market-z.appspot.com',
    iosClientId: '656885086584-jdh4ct9th4g009ufdog35h4rgh1qine7.apps.googleusercontent.com',
    iosBundleId: 'com.example.alHashmiMarket',
  );
}
